version: '3.8'

services:
  universal-file-drop:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Persist uploaded files and database
      - uploads_data:/app/backend/uploads
      - database_data:/app/backend/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - uploads_data:/var/www/uploads:ro  # Serve uploads directly via caddy
    depends_on:
      - universal-file-drop
    restart: unless-stopped
    networks:
      - app-network

volumes:
  uploads_data:
  database_data:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
