version: '3.8'

services:
  universal-file-drop:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Persist uploaded files and database
      - ./data/uploads:/app/backend/uploads
      - ./data/database:/app/backend/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Caddy reverse proxy for production
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - universal-file-drop
    restart: unless-stopped
    profiles:
      - production  # Only start with --profile production

volumes:
  uploads:
  database:
  caddy_data:
  caddy_config:
